## Numpy

## Simple 1 d numy array

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
my_arr = np.array(a)
my_arr

## or====> np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

### Making numpy array from user input 

In [3]:
a = []
total_size = int(input('Enter a Size: '))
for i in range(total_size):
    number = int(input('Enter a number: '))
    a.append(number)

my_array = np.array(a)
my_array

Enter a Size: 3
Enter a number: 1
Enter a number: 2
Enter a number: 3


array([1, 2, 3])

### 2d array 

In [4]:
two_dim = [[1,2,3], [3,4,5], [6,7,8]]
array = np.array(two_dim)
array

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
print('Dimension of array is: ', array.ndim)
print('Size of array is: ', array.shape)

Dimension of array is:  2
Size of array is:  (3, 3)


### Some Numpy Functions 

### Zeros, ones

In [9]:
my_array = np.zeros(3)
my_array

array([0., 0., 0.])

In [11]:
my_array = np.zeros((3,3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
my_1array = np.ones((2,3))
my_1array

array([[1., 1., 1.],
       [1., 1., 1.]])

## eye 
This function creates an array with all diagonal elements as 1 and rest as 0

In [15]:
eye_function = np.eye(3)
eye_function

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
eye_function2 = np.eye(3,3)
eye_function2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### diag 
This function creates the two dimensional array  with all the diagonal elements as the given value

In [18]:
diag_function = np.diag([1,2,4])
diag_function

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

### randint
This function is used to generate the numbers between the given range <br>
Syntax rand(min, max, total_values)

In [20]:
arr = np.random.randint(1,7,3)
arr
## output from 1 to 6 (exclude 7)

array([4, 1, 2])

### rand
This function is used to generate the random numbers between 0 and 1

In [22]:
rand_arr = np.random.rand(3)
rand_arr

array([0.64892903, 0.63180763, 0.90319085])

In [24]:
## In 2d array as well
rand_2d_arr = np.random.rand(2,3)
rand_2d_arr

array([[0.0489554 , 0.45758361, 0.25876666],
       [0.61709245, 0.49929354, 0.40689713]])

### randn  
This function is used to generate random values close to 0 include - values

In [32]:
ran_array = np.random.randn(6)
ran_array

array([-0.48226483,  0.50387836, -0.10567616,  0.76228805,  2.38722884,
       -0.53708666])

In [33]:
ran_array.size

6

In [35]:
for i in range(ran_array.size):
    print(ran_array[i])

-0.4822648293582355
0.5038783598458138
-0.10567616260548367
0.7622880474569715
2.3872288439266134
-0.5370866620127085


### Slicing and indexing in Numpy 

In [39]:
empty_list = []
total_size = int(input('Enter total size: '))

for i in range(total_size):
    number = int(input('Enter a number: '))
    empty_list.append(number)
    
numpy_arr = np.array(empty_list)
print('Converted into numpyarr', numpy_arr)

## Indexing the numpy array
for i in range(numpy_arr.size):
    print(numpy_arr[i])
    
## sum values through indexing
summ = 0
size = numpy_arr.size
for i in range(size):
    summ += numpy_arr[i]
print(summ)

print('*' * 20)

## Indexing

indexing_of_arr = numpy_arr[2:4]
print('index result = ', indexing_of_arr)

Enter total size: 5
Enter a number: 7
Enter a number: 2
Enter a number: 1
Enter a number: 6
Enter a number: 8
Converted into numpyarr [7 2 1 6 8]
7
2
1
6
8
24
********************
index result =  [1 6]


### Reshaping numpy array 
From 1d to 2d or vice versa

In [40]:
## Creating 1d array
arr = np.random.randint(1,100,12)
arr

array([82, 16, 48, 21, 94, 97, 33, 18, 59, 83, 52, 22])

In [41]:
## converting above 1d array to 2d
array_2d = arr.reshape(4,3)  ### means 4 rows and 3 columns (4*3 = 12) otherwise it will give error
array_2d

array([[82, 16, 48],
       [21, 94, 97],
       [33, 18, 59],
       [83, 52, 22]])

In [44]:
## again converting 2d array to 1d
arr_1d = arr.reshape(12)
arr_1d

array([82, 16, 48, 21, 94, 97, 33, 18, 59, 83, 52, 22])

In [62]:
print('Before reshaping Dimension is: ', array_2d.ndim)
print('Before reshaping Size is: ', array_2d.size)
print('Before reshaping shape is: ', array_2d.shape)

print('*' * 25)
print('After reshaping Dimension is: ', arr_1d.ndim)
print('After reshaping Size is: ', arr_1d.size)
print('After reshaping Shape is: ', arr_1d.shape)



Before reshaping Dimension is:  2
Before reshaping Size is:  12
Before reshaping shape is:  (4, 3)
*************************
After reshaping Dimension is:  1
After reshaping Size is:  12
After reshaping Shape is:  (12,)


### -1 concept 

In [63]:
arr = np.random.randint(1,100, 20)
arr

array([62, 99,  8, 65, 91, 25, 65,  8, 54, 91,  8, 43, 21, 71, 48, 90,  3,
       70,  7, 80])

In [64]:
reshape_arr_to_2d =arr.reshape(5, -1)
reshape_arr_to_2d
### Here we define row size i.e. 5 but we don't define column size and we write (-1) so the system automatically calculate row
## 5 * _ = 20   ====> 4 so total column 4

array([[62, 99,  8, 65],
       [91, 25, 65,  8],
       [54, 91,  8, 43],
       [21, 71, 48, 90],
       [ 3, 70,  7, 80]])

In [66]:
reshape_arr_to_2d_another = arr.reshape(-1, 10)
reshape_arr_to_2d_another
## Here we don't define row but define column and it automatically generated total rows (_ * 10 = 20) i.e (2 * 10 = 20)

array([[62, 99,  8, 65, 91, 25, 65,  8, 54, 91],
       [ 8, 43, 21, 71, 48, 90,  3, 70,  7, 80]])

### seed function 
Basically when we use random.randint every time we execute different values is generated but if we use seed function
same number is generated

In [70]:
np.random.seed(12)# Can give any number and if we give another number 10 will generated another set of number but everytime same
np.random.randint(1,100,10)

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

### Creating 2 dimensional array user input 

In [72]:
rows = int(input('Enter total number of rows: '))
columns = int(input('Enter total number of columns: '))
matrix = []

for i in range(rows):
    a = []
    for j in range(columns):
        val = int(input('Enter a number: '))
        a.append(val)
    matrix.append(a)
    
arr = np.array(matrix)
print('numpy array: ', arr)


for i in range(rows):
    for j in range(columns):
        print(arr[i][j], end=" ")
    print()
        
        

Enter total number of rows: 3
Enter total number of columns: 3
Enter a number: 1
Enter a number: 2
Enter a number: 3
Enter a number: 4
Enter a number: 5
Enter a number: 6
Enter a number: 7
Enter a number: 8
Enter a number: 9
numpy array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3 
4 5 6 
7 8 9 


### Slicing 2d array example 

In [74]:
arr = np.random.randint(1,100,20).reshape(5,4)
arr

array([[53,  6, 14, 90],
       [35, 76, 75,  1],
       [77, 14, 83, 90],
       [36, 63, 36, 34],
       [31, 64, 97, 19]])

In [75]:
## Slicing arr =====> arr[row_range,column_range]
arr[1:3,2:]

array([[75,  1],
       [83, 90]])

In [76]:
arr[2:,-1]

array([90, 34, 19])

In [77]:
arr[2:4,2:4]

array([[83, 90],
       [36, 34]])

### Condition Selection in Numpy 

In [91]:
arr = np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [92]:
a = arr > 10
a

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [93]:
### print even numbers
b = arr[arr%2 == 0]
b

array([ 2,  4,  6,  8, 10, 12, 14])

In [94]:
c = arr[arr<5]
c

array([1, 2, 3, 4])

In [96]:
d = arr[arr>10]=0

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0])

### various other operations in Numpy


In [110]:
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

In [111]:
arr1

array([1, 2, 3, 4])

In [112]:
arr2

array([5, 6, 7, 8])

In [113]:
print(arr1 + arr2)
print(arr1*2)
print(arr1**2)
print(arr1**arr2)

[ 6  8 10 12]
[2 4 6 8]
[ 1  4  9 16]
[    1    64  2187 65536]


#### For 2 dim 

In [128]:
arr1 = np.array([1,2,3,4]).reshape(2,2)
arr2 = np.array([4,5,6,7]).reshape(2,2)

In [129]:
arr1

array([[1, 2],
       [3, 4]])

In [130]:
arr2

array([[4, 5],
       [6, 7]])

In [131]:
arr1 + arr2

array([[ 5,  7],
       [ 9, 11]])

In [132]:
arr1 * 2

array([[2, 4],
       [6, 8]])

In [133]:
arr1 ** arr2

array([[    1,    32],
       [  729, 16384]], dtype=int32)

In [134]:
arr1 * arr2
## Multiplication done using numpy

array([[ 4, 10],
       [18, 28]])

### dot 

In [135]:
arr1.dot(arr2)
### like we done in mathematics

array([[16, 19],
       [36, 43]])

### Various Numpy array Functions 

In [136]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [147]:
min_function = np.min(arr)
print('Minimum Number' ,min_function)

max_function = np.max(arr)
print('Maximum Number', max_function)

arg_min_function = np.argmin(arr)
print('Arg min', arg_min_function) ## In 0 index there is 10 which is minimum value in list so print ==> 0

arg_max_function = np.argmax(arr)
print('Arg max', arg_max_function) ## Vice versa of above

square_root_function = np.sqrt(arr)
print('Square Root',square_root_function)

sin_function = np.sin(arr)
print('Sin ', sin_function)

cos_function = np.cos(arr)
print('Cos', cos_function)

lin_space_function = np.linspace(1,10,3)
print('Line Space', lin_space_function) ### From 1 to 9 prints 3 numbers which is equal to the difference

Minimum Number 10
Maximum Number 50
Arg min 0
Arg max 4
Square Root [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Sin  [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cos [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
Line Space [ 1.   5.5 10. ]


In [148]:
np.random.seed(122)
matrix = np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [150]:
np.sum(matrix, axis=0)

array([36, 40, 40])

In [156]:
np.random.seed(111)
arr = np.random.randint(1,21,9)
arr


array([13, 20, 10,  3, 19,  9,  8,  8, 13])

In [160]:
## Shuffle
np.random.shuffle(arr)
arr

array([13,  8, 13,  9, 19, 10, 20,  3,  8])

In [161]:
## Unique element

unique_elements = np.array([1,2,3,1,1,2,3,6])
unique_elements

array([1, 2, 3, 1, 1, 2, 3, 6])

In [162]:
np.unique(unique_elements)

array([1, 2, 3, 6])

In [163]:
## Additional info 
np.unique(unique_elements, return_index=True, return_counts=True)
## First unique elements
## Second index of unique elements
## Third total count of elements in list

(array([1, 2, 3, 6]),
 array([0, 1, 2, 7], dtype=int64),
 array([3, 2, 2, 1], dtype=int64))

### Stacking (Horizontal and vertical Stacking in Numpy) 

In [166]:
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(10,20,5)

In [169]:
horizontal_stack = np.hstack((arr1,arr2))
horizontal_stack

array([ 7,  9,  1,  2,  4, 14, 15, 15, 15, 10])

In [170]:
vertical_stack = np.vstack((arr1,arr2))
vertical_stack

array([[ 7,  9,  1,  2,  4],
       [14, 15, 15, 15, 10]])

#### For 2d

In [171]:
arr_2d_1 = np.random.randint(1,100,9).reshape(3,3)
arr_2d_2 = np.random.randint(4,100,9).reshape(3,3)


In [172]:
arr_2d_1

array([[34, 33,  8],
       [99, 55, 44],
       [79, 72, 51]])

In [173]:
arr_2d_2

array([[66, 79, 44],
       [46, 54, 95],
       [78, 46, 44]])

In [178]:
horizontal = np.hstack((arr_2d_1, arr_2d_2))
horizontal

array([[34, 33,  8, 66, 79, 44],
       [99, 55, 44, 46, 54, 95],
       [79, 72, 51, 78, 46, 44]])

In [179]:
vertical = np.vstack((arr_2d_1, arr_2d_2))
vertical

array([[34, 33,  8],
       [99, 55, 44],
       [79, 72, 51],
       [66, 79, 44],
       [46, 54, 95],
       [78, 46, 44]])

## List and Numpy

Performance, Fast and Flexible (Numpy over List)

In [180]:
%timeit [i**2 for i in range(1,11)]

3.13 µs ± 55.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [181]:
%timeit np.arange(1,11) **2

1.5 µs ± 47.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Searching an element in Numpy 

In [183]:
arr = np.array([1,2,3,4,5,4])
x = np.where(arr == 4)
x

## means 4 is present in index 3 and 5

(array([3, 5], dtype=int64),)

In [185]:
y = np.where(arr%2 == 0)
y

(array([1, 3, 5], dtype=int64),)

### SearchSorted 
This method performs a binary search in the array, and return the index where the specified value would be inserted to maintain
search order (Default search will be from left to right)

In [190]:
a = np.array([2,3,5,9,10])
x = np.searchsorted(a,7) ## Default left side
print(x)


## Can also search from right side
# y = np.searchsorted(a,7,side='right')
# y


3